[simulation]
boundary_absorption = 1
air_absorption_alpha1 = 0.0
air_absorption_alpha2 = 0.0
duration = 0.2
c0 = 343.5
n_pml_layers = 5
asset_name = hall

# User chooses between: coarse, fine, finer, finest
precision = coarse

# Enable or disable response recording
is_record_response = false

# Enable or disable field recording
is_record_field = false

# How many steps to skip in visualization
viz_skip = 10

# Fixed panel size in pixels
fixed_panel_size = 400

# Maximum visualization gain (prevents zooming into artifacts)
max_viz_gain = 100
